version: "3.9"

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - backend-network

  backend:
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    expose:
      - "8000"
    container_name: django_backend
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - envs/stage/django/.env_django
    networks:
      - backend-network
  
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/stage/db/.env_db
    networks:
      - backend-network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/deault.conf
      - static_volume:/home/app/static/
      - media_volume:/home/app/media/
    depends_on:
      - backend
      - db
    networks:
      - backend-network
  
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - backend
    volumes:
     - ./core:/app
    networks:
      - backend-network


volumes:
  redisdata:
  static_volume:
  media_volume:
  postgres_data:

networks:
  backend-network: