version: "3.9"

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    container_name: todobackend
    restart: always
    depends_on:
      - redis
    environment:
      - SECRET_KEY=django-insecure-&)#)fsnkv!^8%6uf0*ny(6!64i!mb%-jwf3_rkosm23e4*59!8
      - DEBUG=True
  
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - backend
    volumes:
     - ./core:/app

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
  redisdata: