version: "3.9"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    container_name: todobackend
    restart: always
    environment:
      - SECRET_KEY=django-insecure-&)#)fsnkv!^8%6uf0*ny(6!64i!mb%-jwf3_rkosm23e4*59!8
      - DEBUG=True
  
  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    restart: always
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  worker:
    image: locustio/locust
    restart: always
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
volumes:
  smtp4dev-data: